version: '3'
services:
  db:
    build: ./db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped

  web:
    build: ./web
    ports:
      - 5000:5000
    links:
      - db
    environment:
      DATABASE_URL: postgresql://testuser:testpass@db:5432/testdb
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - 80:80
    links:
      - web
    restart: unless-stopped
